### ISSUE TITLE
Link in contents doesn’t scroll to content

### ISSUE THREAD

**Issue by shanecarmody** [thlorenz/doctoc#115]
My table of contents was generated perfectly and I can see that my link has been populated with the necessary attributes:

<img width="559" alt="capture d ecran 2016-07-28 a 12 48 57" src="https://cloud.githubusercontent.com/assets/433990/17210270/cb8a1d8e-54c1-11e6-81aa-34c618657e8a.png">

I can also see that my headings have been populated with the necessary attributes:

<img width="582" alt="capture d ecran 2016-07-28 a 12 50 17" src="https://cloud.githubusercontent.com/assets/433990/17210288/e964518a-54c1-11e6-8e2d-1bfa6f2071a4.png">

However, when I click a link in the TOC, it neither takes me to the content nor smooth scrolls to the content. 

I’m not sure why this is happening because I’m getting no errors in the console. Anybody see a reason why?

**Comment by jez** [comment]
I've noticed in various places as well. For example, this usually happens to me a lot on mobile.

As far as I can tell though, all the generated HTML is correct, which means that presumably the generated Markdown is correct as well, leading me to believe that this is not an issue with Doctoc.

Some tips for debugging:

- Are you using a JavaScript framework that hijacks the browser's normal hash link handling? (for example, React Router)
- Have you tried using `id="styleguide"` in place of `name="styleguide"`?
- Is it not scrolling because there's not enough content on the page to scroll down?

Hope you can figure it out.
