### ISSUE TITLE
Create title with base in title parameter on jekyll (github) markdown file

### ISSUE THREAD

**Issue by carlosdelfino** [thlorenz/doctoc#116]
I need create the title of TOC which base in header parameter `title` in jekyll md files. And identify of level this title on new TOC.

This files can find in link: https://github.com/carlosdelfino/micro-os-plus.github.io-source/blob/a72914859eaeb98dea13b7469a0db80432269584/pages/user-manual/basic-concepts.pt.md

And similar result in: https://github.com/carlosdelfino/micro-os-plus.github.io-source/blob/a72914859eaeb98dea13b7469a0db80432269584/pages/user-manual/basic-concepts.toc.pt.md

**Comment by jez** [comment]
You can already change the title of the TOC using the `--title` flag at the command line. While there isn't an option to pull the title from the Jekyll frontmatter, you should still be able to write a small shell script to do this. It could extract the title from the frontmatter and pass it to the `--title` flag.

Again, I think this is a bit of a niche feature that adds more complexity than it's worth, so I'm going to close this unless @thlorenz feels otherwise.
