### ISSUE TITLE
Not adding a Heading

### ISSUE THREAD

**Issue by RyanZim** [thlorenz/doctoc#121]
@thlorenz I found a weird bug.

On the README for https://github.com/RyanZim/awesome-npm-scripts, doctoc refuses to add the `Dev Servers` heading to the table of contents. I manually added it, and every time I run doctoc, it removes it. This happens with the latest release and `master`.

Any idea what's causing this?

**Comment by maxlath** [comment]
Ok, so I found the issue: it appears my dumb text editor inserted a non-breaking space instead of a normal white space [line 46](https://github.com/RyanZim/awesome-npm-scripts/blob/master/README.md#L46), making doctoc unable to parse it correctly I imagine. After replacing the non-breaking space, doctoc does work as expected. Apologies for the troubles

**Comment by RyanZim** [comment]
@thlorenz Do we support non-standard spaces?

**Comment by thlorenz** [comment]
No @RyanZim let's stick with standard spaces.
Ideally we'd add a linting step to the tests, i.e. we could run my own version of standard, [standart](https://github.com/thlorenz/standart).
However I believe you'd get a lot of violations at this point and I doubt you wanna clean those up :(

**Comment by RyanZim** [comment]
OK, thanks to everyone.

**Comment by thlorenz** [comment]
Seems like I misunderstood the question there a bit. So the project in question should probably add a linter. Happy it all got resolved :)
