### ISSUE TITLE
doctoc crashes when space in filename

### ISSUE THREAD

**Issue by keverw** [thlorenz/doctoc#127]
```shell
doctoc 'README - add to.md'
fs.js:907
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat 'README\ -\ add\ to.md'
    at Object.fs.statSync (fs.js:907:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/doctoc/doctoc.js:103:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

I'm not too sure how important this bug would be, as it seems like not using spaces is better anyways. Discovered this when asking for help on #80

**Comment by jez** [comment]
As far as I can tell, this is the [offending line][1]. It looks to have been introduced by this commit: 994839f1cb5e2c4c75ba712f5de4cc3aa4438919.

@thlorenz: The message for that commit makes it look like this line was added intentionally. Is it safe to remove this line, or is there something else we should be aware of?

To explain further, it seems like we manually escape spaces in filenames, which in turn causes `fs.statFile` to fail, because it looks for a file named 'foo\ bar.md' instead of 'foo bar.md'.

[1]: https://github.com/thlorenz/doctoc/blob/b96694ff868962cb93054d3913ebd3bda8d26fda/doctoc.js#L15-L16

**Comment by thlorenz** [comment]
@jez I think we should write a test that shows the problem and make sure it gets fixed by removing the offending line.
Afaik escaping spaces should only be necessary directly on the command line, but since this gets handled by node `fs` module we shouldn't need to.

I added that line myself and can't quite remember the reasoning behind it.

**Comment by jez** [comment]
> I think we should write a test that shows the problem and make sure it gets fixed by removing the offending line.

Our testing infrastructure currently doesn't test any of the argument parsing or IO code, does it?

**Comment by andrii-kovalenko-ct** [comment]
Got this issue today, pls - fix

**Comment by thlorenz** [comment]
> Our testing infrastructure currently doesn't test any of the argument parsing or IO code, does it?

No it does not, so we'd need to setup CLI tests for this @jez . I understand if that's a bit much to ask, but would be great to have also going forward.

Otherwise we could just fix the issue for now without the test.

**Comment by alf-p-steinbach** [comment]
In Windows a workaround is to use the DOS 8+1 shortname. The shortnames are shown by Cmd `dir /x` and can be obtained e.g. via the `for` command:

```txt
[T:\]
> for %f in ("*.md") do @echo "%f" → "%~sf"
"00 about.md" → "T:\00ABOU~1.MD"
"01 Preparation.md" → "T:\01PREP~1.MD"
```
A different workaround could be to use hard or symbolic links.

**Comment by alf-p-steinbach** [comment]
Escaping spaces in the path is a Unix-specific kludge. It leaves the function name `cleanPath`  an oxymoron.

Instead of this stringly typed handling I would represent paths via instances of a class `Path` with suitable behavior for each platform.

I like DocToc but I find it annoying to have to work around this bug all the time.
