### ISSUE TITLE
TOC headers with emoji create broken relative-links

### ISSUE THREAD

**Issue by kevinwkt** [thlorenz/doctoc#191]
When I seem to use emojis like the image below:
![image](https://user-images.githubusercontent.com/16668571/103548711-d2cc3e80-4e6b-11eb-872f-4a2aa700f41d.png)

Doctoc generates the following:
![image](https://user-images.githubusercontent.com/16668571/103548486-7ec15a00-4e6b-11eb-8831-3b7dde852040.png)

The only valid relative-link seems to be 'Staging' while the rest needs manual update to the following to work:
![image](https://user-images.githubusercontent.com/16668571/103548646-b9c38d80-4e6b-11eb-83a1-5490f8b8d539.png)

Wanted to know if I create a PR that fixes this it would be accepted.

**Comment by AndrewSouthpaw** [comment]
Sure! Seems like a great thing to fix. Emojis are important 😄

**Comment by kevin-david** [comment]
After some investigation of this issue, I think it's due to the usage of `anchor-markdown-header` which has had it's last update 5 years ago: https://www.npmjs.com/package/anchor-markdown-header 

Specifically this function call: https://github.com/thlorenz/doctoc/blob/0608762802672dd9b45658a7f2fc85b8984b1b42/lib/transform.js#L25

It looks like emoji-regex is relatively up to date, so perhaps just a newer package update would do it: https://www.npmjs.com/package/emoji-regex

I will keep investigating...

**Comment by kevin-david** [comment]
Upgrading `emoji-regex` in `anchor-markdown-header` did indeed fix this issue: https://github.com/thlorenz/anchor-markdown-header/pull/45

It might take a few cascading dependency/package updates to actually get all these merged back into this library update though.

/cc: @thlorenz
