### ISSUE TITLE
Hyperlinked heading is linked with heading's hyperlink, not heading anchor

### ISSUE THREAD

**Issue by geremyCohen** [thlorenz/doctoc#69]
Hi, very cool project here! I did notice an issue when using with my README:

I have a heading that is linked (not sure if this is bad form, probably is):

```
##### [CNN](https://www.cnn.com)
```

When doctoc is run against this README, it renders the TOC entry as so:

```
 - [[CNN](https://www.cnn.com)](...urlpathstuff#cnn)
```

So when I client on this TOC entry, it sends me to www.cnn.com, not #cnn

tia
geremy

**Comment by bkuhlmann** [comment]
In case it helps, I'm seeing this issue as well. Take a look at the headings (with links) as defined in the Alias and Function sections of this [README](https://github.com/bkuhlmann/dotfiles/blob/release/README.md). I had to remove most of the auto-generated *Usage* section since headings with links cause a lot of conflicts. This is what the TOC *would* look like if generated by DocToc without any editing:

![bad_toc](https://cloud.githubusercontent.com/assets/50245/8891546/d2739c72-32eb-11e5-9bbc-030e345e407d.png)
