### ISSUE TITLE
TOC creates invalid links when headers have inline images.

### ISSUE THREAD

**Issue by Daenyth** [thlorenz/doctoc#73]
Example README: https://github.com/Cockatrice/Cockatrice/blob/dfd5c5e050e2abee5c3e2f7b6b0ae0387ced46e8/README.md

**Comment by jez** [comment]
So the root cause of both this issue as well as #69 is that we're not treating headers as Markdown; rather we're treating them as plain text and doing some simple regex transformation on that text.

What we should be doing is parsing headers into something like a syntax tree for Markdown, determining what text is actually displayed vs. hidden per Markdown's rules, and rendering an anchor tag in the ToC accordingly.

/cc @thlorenz
